spring:
  application:
    name: library-system

  datasource:
    url: jdbc:postgresql://localhost:5432/library-data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

